language: php

dist: trusty

sudo: false

php:
    - 7.1
    - 7.2

matrix:
    fast_finish: true

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - $SYLIUS_CACHE_DIR

env:
    global:
        - SYLIUS_CACHE_DIR=$HOME/.sylius-cache
    matrix:
       - DEPENDENCY_VERSIONS="sylius/sylius:1.2.* symfony/symfony:4.1.*"
       - DEPENDENCY_VERSIONS="sylius/sylius:1.2.* symfony/symfony:3.4.*"
       - DEPENDENCY_VERSIONS="sylius/sylius:1.1.* symfony/symfony:3.4.*"
       - DEPENDENCY_VERSIONS="sylius/sylius:1.0.* symfony/symfony:3.4.*"

before_install:
    - phpenv config-rm xdebug.ini
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - mkdir -p "${SYLIUS_CACHE_DIR}"

install:
    - composer update --prefer-dist
    - (cd tests/Application && yarn install)
    - npm install gulp gulp-concat gulp-chug gulp-debug gulp-if gulp-livereload gulp-order gulp-sass
    - npm install gulp-sourcemaps gulp-uglify gulp-uglifycss jquery lightbox2
    - npm install merge-stream semantic-ui-css yargs

before_script:
    - mkdir -p build/logs

    - (cd tests/Application && bin/console doctrine:database:create --env=test -vvv)
    - (cd tests/Application && bin/console doctrine:schema:create --env=test -vvv)
    - (cd tests/Application && bin/console assets:install web --env=test -vvv)
    - (cd tests/Application && yarn run gulp)

    # Configure display
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1680x1050x16
    - export DISPLAY=:99

    # Download and configure ChromeDriver
    - |
        if [ ! -f $SYLIUS_CACHE_DIR/chromedriver ] || [ "$($SYLIUS_CACHE_DIR/chromedriver --version | grep -c 2.34)" = "0" ]; then
            curl http://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip > chromedriver.zip
            unzip chromedriver.zip
            chmod +x chromedriver
            mv chromedriver $SYLIUS_CACHE_DIR
        fi

    # Run ChromeDriver
    - $SYLIUS_CACHE_DIR/chromedriver > /dev/null 2>&1 &

    # Download and configure Selenium
    - |
        if [ ! -f $SYLIUS_CACHE_DIR/selenium.jar ] || [ "$(java -jar $SYLIUS_CACHE_DIR/selenium.jar --version | grep -c 3.4.0)" = "0" ]; then
            curl http://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar > selenium.jar
            mv selenium.jar $SYLIUS_CACHE_DIR
        fi

    # Run Selenium
    - java -Dwebdriver.chrome.driver=$SYLIUS_CACHE_DIR/chromedriver -jar $SYLIUS_CACHE_DIR/selenium.jar > /dev/null 2>&1 &

    # Run webserver
    - (cd tests/Application && bin/console server:run 127.0.0.1:8080 -d web --env=test --quiet > /dev/null 2>&1 &)

script:
    - composer validate --strict --no-check-all
    - vendor/bin/phpspec run
    - vendor/bin/behat -vvv --no-interaction || vendor/bin/behat -vvv --no-interaction --rerun
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --stderr --verbose

after_script:
     - wget https://scrutinizer-ci.com/ocular.phar
     - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

after_success:
     - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.0/coveralls.phar
     - chmod +x coveralls.phar
     - travis_retry php coveralls.phar -v
